language: python

python:
  - "3.5"

services:
  - mongodb
  
install:
  - pip install -r requirements.txt
  
before_script:
  mongorestore -d openuniverse dump/openuniverse
  
script:
  python manage.py test
