language: python

python:
  - "3.5"

services:
  - mongodb
  
install:
  - pip install -r requirements.txt
  
before_script:
  mongorestore --db openuniverse mongodb/projects.bson
  
script:
  python manage.py test
